create table if not exists public.auto_episodes (
  id bigint generated by default as identity primary key,
  source text not null default 'franime',
  source_page text not null unique,
  anime_slug text not null,
  anime_title text not null,
  season_number integer not null check (season_number > 0),
  episode_number integer not null check (episode_number >= 0),
  language text not null check (language in ('VF','VOSTFR')),
  embed_url text not null check (embed_url ~ '^https://sendvid.com/embed/[A-Za-z0-9_-]+'),
  poster_url text,
  description text,
  published boolean not null default true,
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists auto_episodes_recent_idx
  on public.auto_episodes (created_at desc)
  where published = true;

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  discovered integer not null default 0,
  saved integer not null default 0,
  skipped integer not null default 0,
  failed integer not null default 0,
  finished_at timestamptz not null default now()
);

alter table public.auto_episodes enable row level security;
alter table public.sync_runs enable row level security;

drop policy if exists "Public can read published auto episodes" on public.auto_episodes;
create policy "Public can read published auto episodes"
  on public.auto_episodes for select
  using (published = true);

revoke all on public.sync_runs from anon, authenticated;
grant select on public.auto_episodes to anon, authenticated;
